name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: saml-to/assume-aws-role@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        role: "arn:aws:iam::300301835588:role/github-admin"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag web-app:$(date +%s)
